# Generated by Django 5.2.8 on 2025-11-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('juices', 'Juices')], max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('productimage', models.ImageField(default=True, upload_to='product_doc')),
            ],
        ),
    ]
