# Generated by Django 5.2.8 on 2025-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
    ]
