# Generated by Django 5.2.8 on 2025-11-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slice2Cook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
