# Generated by Django 5.2.8 on 2025-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slice2Cook', '0002_alter_user_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('experience', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('adminapprove', models.BooleanField(default=False)),
                ('adminreject', models.BooleanField(default=False)),
            ],
        ),
    ]
