# Generated by Django 5.2.8 on 2025-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slice2Cook', '0003_employee_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_registration',
            name='experience',
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='idproof',
            field=models.ImageField(default=True, upload_to='idproof'),
        ),
    ]
