# Generated by Django 5.2.8 on 2025-12-29 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slice2Cook', '0004_remove_employee_registration_experience_and_more'),
        ('vegadmin', '0002_add_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField()),
                ('amount', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegadmin.add_items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slice2Cook.user_registration')),
            ],
        ),
    ]
