# Generated by Django 5.2.8 on 2025-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slice2Cook', '0005_user_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
