# Generated by Django 5.2.8 on 2025-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slice2Cook', '0006_user_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='suggestions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
