# Generated by Django 5.2.8 on 2025-12-30 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slice2Cook', '0007_user_booking_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
