# Generated by Django 5.2.8 on 2025-11-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('phonenumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=80)),
                ('time', models.CharField(max_length=50)),
                ('license', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
