# Generated by Django 5.2.8 on 2025-11-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_registration',
            name='adminapprove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery_registration',
            name='adminreject',
            field=models.BooleanField(default=False),
        ),
    ]
