# Generated by Django 5.2.8 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deliverapp', '0002_delivery_registration_adminapprove_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_registration',
            name='license',
        ),
        migrations.AddField(
            model_name='delivery_registration',
            name='liscenceimg',
            field=models.ImageField(default=True, upload_to='liscencedoc'),
        ),
    ]
